# Generated by Django 5.0.6 on 2024-07-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_attribute_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
