# Generated by Django 5.0.6 on 2024-07-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_attribute_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='text',
        ),
    ]
